name: Forms
package-name: aldryn-forms
url: https://github.com/aldryn/aldryn-forms
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - emailit
  - captcha
  - aldryn_forms
version: 0.0.1
description: Create forms and embed them on CMS pages
license:
  name: BSD
  text: !literal-include LICENSE.txt
